# Generated by Django 6.0.3 on 2026-03-30 23:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(db_comment='Primary key', help_text='The primary key for the job application', primary_key=True, serialize=False, verbose_name='id')),
                ('user', models.BigIntegerField(db_column='user_id', db_comment='The user who submitted the application.', verbose_name='user id')),
                ('when', models.DateField(blank=True, db_comment='Date of application.', default=django.utils.timezone.localtime, help_text='The date when the application was submitted', verbose_name='when')),
                ('company', models.CharField(db_comment='Name of company.', help_text='The name of the company.', max_length=64, verbose_name='company name')),
                ('title', models.CharField(db_comment='Job title.', help_text='The job title.', max_length=128, verbose_name='job title')),
                ('posting', models.URLField(blank=True, db_comment='URL of job posting, if applicable.', help_text='The URL for the job posting, if applicable. Use notes for other job sources', null=True, verbose_name='job posting url')),
                ('confirm', models.URLField(blank=True, db_comment='URL for application confirmation, if applicable.', help_text='The URL of the confirmation email', null=True, verbose_name='confirmation email url')),
                ('notes', models.TextField(blank=True, db_comment='Notes', help_text='Notes about this job, such as alternate sources, expected salary, etc.', max_length=4096, null=True, verbose_name='notes')),
                ('active', models.BooleanField(db_comment='Application is still outstanding.', default=True, help_text='True if the job application is still potentially active', verbose_name='application still active')),
                ('interviews', models.PositiveSmallIntegerField(db_comment='The number of interviews for the job.', default=0, help_text='The number of interviews. More details like dates can go in the notes field.', verbose_name='interviews')),
                ('rejected', models.DateField(blank=True, db_comment='Date of rejection notice.', help_text='When a job rejection letter was received', null=True, verbose_name='rejection date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Record created at.', help_text='When the record was created', null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Record last updated at.', help_text='When the record was last updated', verbose_name='updated_at')),
            ],
            options={
                'db_table': 'job_applications',
            },
        ),
    ]
