# Generated by Django 6.0.4 on 2026-05-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_jobapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='posting',
            field=models.URLField(blank=True, db_comment='URL of job posting, if applicable.', help_text='The URL for the job posting, if applicable. Use notes for other job sources', max_length=2048, null=True, verbose_name='job posting url'),
        ),
    ]
