services:
  py-wsgi:
    build:
      context: .
      dockerfile: ./docker/py-wsgi/Dockerfile.prod
      tags:
        - unemployment-py-wsgi:latest
      target: production
    image: unemployment-py-wsgi
    env_file:
      - ./.env
    command: gunicorn unemployment.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/var/www/unemployment/web/staticfiles
      - media_volume:/var/www/unemployment/web/mediafiles
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
      tags:
        - unemployment-web:latest
    image: unemployment-web
    volumes:
      - static_volume:/var/www/unemployment/web/staticfiles
      - media_volume:/var/www/unemployment/web/mediafiles
    ports:
      - 8000:80
    depends_on:
      - py-wsgi
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


volumes:
  static_volume:
  media_volume:
