services:
  py-wsgi:
    build:
      context: .
      dockerfile: ./docker/py-wsgi/Dockerfile.prod
      tags:
        - ${REGISTRY}/unemployment-py-wsgi:${TAG}-debug
        - ${REGISTRY}/unemployment-py-wsgi:latest-debug
      target: production
    image: ${REGISTRY}/unemployment-py-wsgi:latest-debug
    command: gunicorn
    volumes:
      - static_volume:/var/www/unemployment/web/staticfiles
      - media_volume:/var/www/unemployment/web/mediafiles
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE}
    secrets:
      - source: unemployment_debug_env
        target: /var/www/unemployment/web/.env
        mode: 0400
        uid: '0'
        gid: '0'


  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
      tags:
        - ${REGISTRY}/unemployment-web:${TAG}-debug
        - ${REGISTRY}/unemployment-web:latest-debug
    image: ${REGISTRY}/unemployment-web:latest-debug
    volumes:
      - static_volume:/var/www/unemployment/web/staticfiles
      - media_volume:/var/www/unemployment/web/mediafiles
    ports:
      - 8008:80
    depends_on:
      - py-wsgi
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE}


volumes:
  static_volume:
  media_volume:


secrets:
  unemployment_debug_env:
    external: true
