upstream unemployment {
    server py-wsgi:8000;
}

server {

    listen 80;

    location / {
        proxy_pass http://unemployment-debug;

        # Stuff to make the application aware that we are actually using HTTPS.
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Ensure the proto header is based on the incoming schem (which Apache handles)
        proxy_set_header X-Forwarded-Proto $scheme;

        # Don't rewrite Location and Refresh being sent by the actual application.
        proxy_redirect off;

        # Debugging timeouts
        proxy_connect_timeout   3600s;
        proxy_send_timeout      3600s;
        proxy_read_timeout      3600s;
    }

    location /static/ {
        alias /var/www/unemployment/web/staticfiles/;
    }

    location /media/ {
        alias /var/www/unemployment/web/mediafiles/;
    }
}
