"""
Django settings for unemployment project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
import os

env = environ.Env(DEBUG=(bool, False))

# Set our DEBUG value
DEBUG = env.bool('DEBUG', False)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Get our site name.
SITE_NAME = env('SITE_NAME')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# Google API key
GOOGLE_API_KEY = env('GOOGLE_API_KEY')
GOOGLE_SPREADSHEET_ID = env('GOOGLE_SPREADSHEET_ID')

ALLOWED_HOSTS = env.list('MYHOSTNAME')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_bootstrap5',
    'crispy_forms',
    'rest_framework',
    'applications',
    'applications_api',
    'webpack_loader',
    'widget_tweaks',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'unemployment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'unemployment.context_processors.build_info_processor',
                'unemployment.context_processors.site_name_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'unemployment.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': env.db()
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Email backend
# https://docs.djangoproject.com/en/6.0/topics/email/
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')
SERVER_EMAIL = env('SERVER_EMAIL')

EMAIL_BACKEND = env('EMAIL_BACKEND')
split_list = EMAIL_BACKEND.split('.')
if split_list[-2] == 'filebased':
    EMAIL_FILE_PATH = env('EMAIL_FILE_PATH')
elif split_list[-2] == 'smtp':
    EMAIL_HOST = env('EMAIL_HOST')
    EMAIL_PORT = env('EMAIL_PORT', 25)
    EMAIL_HOST_USER = env.str('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', False)
    EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', False)
    EMAIL_TIMEOUT = env.int('EMAIL_TIMEOUT', None)
    EMAIL_SSL_KEYFILE = env.path('EMAIL_SSL_KEYFILE', None)
    EMAIL_SSL_CERTFILE = env.path('EMAIL_SSL_CERTFILE', None)
elif split_list[-2] == 'console':
    pass
elif split_list[-2] == 'locmem':
    pass
elif split_list[-2] == 'dummy':
    pass
else:
    raise environ.ImproperlyConfigured('Unknown mail backend: {}'.format(split_list[-2]))
del split_list

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = env.str('LANGUAGE_CODE', 'en-us')

TIME_ZONE = env.str('TIME_ZONE', 'America/New_York')

USE_I18N = env.bool('USE_I18N', True)

USE_TZ = env.bool('USE_TZ', True)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Where collectstatic puts files for use in production.
STATIC_ROOT = "staticfiles/"

# Where to search for static files which are not under an installed application.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

WEBPACK_LOADER = {
    'DEFAULT': {
        'STATS_FILE': os.path.join(STATIC_URL, 'webpack_bundles/webpack-stats.json'),
    },
    'APPLICATION_DETAILS': {
        'STATS_FILE': os.path.join(STATIC_URL, 'webpack_bundles/webpack-application-details-stats.json'),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout related settings.
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'
